CREATE TABLE IF NOT EXISTS Signup (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(200),
    Address VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS User (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100) NOT NULL,
    Email VARCHAR(200) NOT NULL,
    Password VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS UserRole (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    Role VARCHAR(100) NOT NULL,
    CONSTRAINT Fk_UserId FOREIGN KEY (UserId) REFERENCES User(Id)
);
